["protostar.config"]
protostar_version = "0.5.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
main = [
    "src/main.cairo",
]

["protostar.shared_command_configs"]
cairo_path = ["./lib/cairo_contracts/src", "./lib/cairo_contracts/src2", "./lib/cairo_contracts/src3"]
